### ISSUE TITLE
When using "step" the program doesn't stop after van crashes

### ISSUE THREAD

**Issue by pawelkrupinski** [ocadotechnology/rapid-router#614] opened 2015-08-18 08:51 UTC
Steps to reproduce:
1. Create a program that crashes the van (or has too few instructions to solve the level)
2. Keep clicking "Step" until the van crashes or it runs out of instructions

You won't be able to clear or edit the program until you click "Play", "Resume" or "Stop".

Desirable behaviour: same as if the van crashed or ran out of instructions after clicking play - so popup with information and options.

**Comment by javicg** [comment] 2015-11-18 17:41
I have tested this on one of the levels and it works as expected:
- Popup comes up after failing
- Program can be cleared without any issues

It looks like the bug does not exist any more.
I will close the issue and see if I can add a test to cover it.

**Comment by javicg** [comment] 2015-11-18 17:49
I managed to reproduce the bug, but it only comes up after crashing (if you ran out of instructions, it works as expected).
I will have a look.

**Closed** 2015-11-18 19:49 UTC
Labels: bug, estimate: 2, game, high priority, ready for pickup, user experience
