### ISSUE TITLE
Level Editor canvas

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1550] opened 2023-12-03 15:22 UTC
**Describe the bug**
The objects on the canvas - the bin and the grid have changed recently, possibly introduced with the autoscaling task.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to level editor
2. See bin and grid are incorrect

**Expected behaviour**
Bin should be bottom right and scale with window

Create task for volunteers once understood

<img width="1463" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0FvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2f7103617ccddd67c9cc4a19f89b7be316b1aac4/Screenshot%202023-12-03%20at%2015.21.28.png" alt="Screenshot 2023-12-03 at 15.21.28.png" />

**Comment by faucomte97** [comment] 2023-12-11 18:11
Duplicate of #1543.

**Closed by faucomte97** 2023-12-11 18:11 UTC
