### ISSUE TITLE
Level 50: Better solution can be found

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/rapid-router#906] opened 2017-05-08 17:24 UTC
![screenshot from 2017-05-08 17-40-19](https://cloud.githubusercontent.com/assets/8862062/25816283/7ca9cd42-341b-11e7-9d93-99c0c211af48.png)

Current solution is not very generic and is longer.

**Comment by mrniket** [comment] 2019-02-11 15:54
Duplicate of #497 . Closing.

**Closed by mrniket** 2019-02-11 15:54 UTC
