### ISSUE TITLE
When workspace is resized horizontally the code can end up under the toolbox

### ISSUE THREAD

**Issue by pawelkrupinski** [ocadotechnology/rapid-router#626] opened 2015-08-18 11:33 UTC
And it doesn't come back by itself even when we go back to the old size / width:
![screen shot 2015-08-18 at 12 32 01](https://cloud.githubusercontent.com/assets/304285/9328968/4e68d740-45a5-11e5-9b46-944643f2ad07.png)
![screen shot 2015-08-18 at 12 32 14](https://cloud.githubusercontent.com/assets/304285/9328970/4fd25b56-45a5-11e5-9d00-231d8d919cc4.png)
![screen shot 2015-08-18 at 12 32 30](https://cloud.githubusercontent.com/assets/304285/9328973/5141576c-45a5-11e5-8324-4fb71dfce709.png)
![screen shot 2015-08-18 at 12 32 40](https://cloud.githubusercontent.com/assets/304285/9328974/52771b3a-45a5-11e5-9747-de11f87bee5c.png)

**Comment by pawelkrupinski** [comment] 2015-11-09 09:51
This is what happens in the code when you decrease the horizontal size of Blockly workspace:
Blockly.WorkspaceSvg.resize is triggered when the window / workspace resizes
it triggers Blockly.ScrollbarPair.resize which changes the position / value of horizontal scrollbar (which is when trouble starts).
Since scrollbar is actually moved / changes value, the 
Blockly.setMainWorkspaceMetrics_ and  Blockly.WorkspaceSvg.translate are called, which move the blocks (but only if they would end up outside the visible area).

It does not reverse this process when you increase the size though.

Here's the stacktrace:
Blockly.WorkspaceSvg.translate (workspace_svg.js:320)
Blockly.setMainWorkspaceMetrics_ (blockly.js:600)
Blockly.Scrollbar.onScroll_ (scrollbar.js:492)
Blockly.Scrollbar.resize (scrollbar.js:298)
Blockly.ScrollbarPair.resize (scrollbar.js:111)
Blockly.WorkspaceSvg.resize (workspace_svg.js:294)
Blockly.svgResize (blockly.js:277)
(anonymous function) (inject.js:464)

**Comment by pawelkrupinski** [comment] 2015-11-11 14:41
UX guys suggested making the toolbox fixed / inline (instead of transparent) to disallow blocks going under it.
We could still make it toggle if we did that.

**Comment by CelineBoudier** [comment] 2016-01-06 13:45
It would be good to disallow blocks from going under it indeed.
One of my friends tried the game and the first thing he told me was: Hey, I managed to drag and drop the start block under the left blocks list... Chrome, linux (I can reproduce the issue)

**Comment by angelabrownsey** [comment] 2016-01-06 18:22
A possible solution for the UX side:
Instead of having command list as an overlay over the workspace, it should be an extension of the lefthandpanel, with the workspace resizing to accommodate this. This would mean that the written program would not be able to be moved under the command list.

**Comment by j4mesholland** [comment] 2019-03-13 09:56
I wonder why we have a closable Blockly toolbox anyway?

If we want to keep it we could still show a hint of what's inside, however, if the user then uses the extra code area, we would need the toolbox to nudge the users Blockly to the right.

**Toolbox fixed, no transparency**
![RR interim Desktop.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/fa7ab1ea-0e3c-480d-9c31-0c95330983f9)

**Collapsed toolbar, peek of toolbox for context**
![Blockly peek Desktop Interim.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/af3e68af-5e78-4ebb-99f2-e959186d2d4c)

**Comment by mrniket** [comment] 2019-03-13 13:42
I would agree with @j4mesholland. Since we focusing on supporting tablets and desktops this doesn't seem like it's needed anymore. My personal preference would be to keep it fixed and see what the feedback is

**Comment by faucomte97** [comment] 2019-03-14 10:14
I agree with @mrniket and @j4mesholland too. Seems good to have it fixed :)

**Comment by j4mesholland** [comment] 2019-03-22 09:05
UX done, handing over to Dev

**Comment by mrniket** [comment] 2019-10-14 13:17
Had a revisit on this, it looks like it's not an issue anymore so I'm closing this issue

**Closed as completed by mrniket** 2019-10-14 13:17 UTC
Labels: dev ops
